#!/bin/sh
set -e

test "$1" = remove || test "$1" = deconfigure || exit 0

# This block does not run if Apache is removed before gitweb.
# In that case there is nothing we can do --- Apache needs to
# take responsibility for undoing what enconf did because
# disconf is not available for use by individual web apps.
if [ -e /usr/share/apache2/apache2-maintscript-helper ]
then
  . /usr/share/apache2/apache2-maintscript-helper
  apache2_invoke disconf gitweb || exit
fi
